money dialog box
gamedev-iitk/tower-defense pull request #59
Opened 2020-04-24 02:26 UTC by rahulv73039

**Changes** 
1.Font Style Changed to Arial for text in dialog box.
2. Text Animation Removed.

**OutStandings**
1. I have Used game objecct GameObject For Initial Money  value.
2. I Have Made Animator Folder for animation of dialog box Up and Down Movement.

2020-04-28 10:45 UTC, mayant15 commented
You've committed your merge conflicts. Please test your PRs throroughly and make sure this doesn't happen in the future. Will fix and merge this one for now.

2020-04-28 11:07 UTC, mayant15 requested changes
You've committed all merge conflicts. Fix it and ensure this doesn't happen in the future. Test your PRs thoroughly. We can discuss how to solve this tonight 👍

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scenes/MainScene.unity
> +<<<<<<< HEAD
Merge conflict start marker

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scenes/MainScene.unity
> +>>>>>>> c4be30b69c51fa199dcd7ae443f7f46b1f44d4cf
Merge conflict end marker

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scripts/UI/UpgradeMenuUISystem.cs
> +<<<<<<< HEAD
Merge conflict start marker

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scripts/UI/UpgradeMenuUISystem.cs
> +>>>>>>> c4be30b69c51fa199dcd7ae443f7f46b1f44d4cf
Merge conflict end marker

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scripts/UI/UpgradeMenuUISystem.cs
> +<<<<<<< HEAD
Merge conflict start marker

2020-04-28 11:07 UTC, mayant15 commented on Assets/Scripts/UI/UpgradeMenuUISystem.cs
> +>>>>>>> c4be30b69c51fa199dcd7ae443f7f46b1f44d4cf
Merge conflict end marker

2020-04-29 07:12 UTC, rahulv73039 commented
i think conflicts are resolved 
In upgrademenu script it was just displacement of text and nothing more  complex
In main scene there was conflicts of adresses i think

2020-04-30 12:57 UTC, mayant15 approved these changes
Apart from a few Git mistakes, the PR seems complete. Will clean it up a bit and merge today.

2020-04-30 12:57 UTC, mayant15 commented on Assets/Scripts/Dialogbox/scoreup.cs
> +    public  int theScore;
Use better variable names, like just `score`

2020-04-30 12:57 UTC, mayant15 commented on Assets/Scripts/UI/UpgradeMenuUISystem.cs
> +
Remove unnecessary blank lines like this one

2020-04-30 12:57 UTC, mayant15 commented on Assets/Tests/PlayMode/MovementTests.cs
> +        /// <summary>
These tests seem to be left-overs from your earlier PRs

2020-04-30 17:31 UTC, merged